## Append samples you want in your CSV to this file as resources ##
resources:
- db-operator_v1alpha1_dbserver.yaml
- db-operator_v1alpha1_db.yaml
- db-operator_v1alpha1_user.yaml
- db-operator_v1alpha1_backuptarget.yaml
- db-operator_v1alpha1_restoretarget.yaml
- db-operator_v1alpha1_backupjob.yaml
- db-operator_v1alpha1_restorejob.yaml
- db-operator_v1alpha1_s3storage.yaml
- db-operator_v1alpha1_restorecronjob.yaml
- db-operator_v1alpha1_dbcopyjob.yaml
- db-operator_v1alpha1_backupcronjob.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
